espressif/idf-build-apps

CHANGELOG.md
idf_build_apps/__main__.py
idf_build_apps/app.py
idf_build_apps/logging.py
idf_build_apps/main.py
idf_build_apps/utils.py

feat: support colored output by default

---

CHANGELOG.md
idf_build_apps/app.py
idf_build_apps/main.py

fix: stop writing app_info and size_info if the build got skipped

---

CHANGELOG.md
idf_build_apps/main.py

also fix the wrong `t` as `target` issues

fix: CLI option --target is required

---

idf_build_apps/main.py

fix: revert breaking change that stop pass TextIO to collect files

---

CHANGELOG.md
idf_build_apps/app.py
idf_build_apps/manifest/if_parser.py
idf_build_apps/manifest/manifest.py
tests/test_finder.py

feat: support new keyword `CONFIG_NAME` in manifest file

---

.github/workflows/test-build-idf-apps.yml
CHANGELOG.md
CONTRIBUTING.md
idf_build_apps/utils.py
pyproject.toml
tests/test_finder.py
tests/test_utils.py

python < 3.5 does not support globstar (**) correctly

fix: glob patterns are matching recursively

---

CHANGELOG.md
idf_build_apps/app.py

feat: support placeholder "@v"

---

.github/workflows/test-build-idf-apps.yml
idf_build_apps/app.py
idf_build_apps/constants.py
idf_build_apps/finder.py
idf_build_apps/main.py
idf_build_apps/utils.py

feat: support build with make

---

idf_build_apps/app.py

feat: skip running idf.py reconfigure when empty modified components

---

idf_build_apps/app.py

feat: skip running idf.py reconfigure when empty modified components (v1.x)

---

idf_build_apps/app.py
idf_build_apps/junit/__init__.py
idf_build_apps/junit/report.py
idf_build_apps/junit/utils.py
idf_build_apps/main.py
tests/test_build.py
tests/test_finder.py
tests/test_manifest.py

feat: support junit output for build_apps

---

idf_build_apps/app.py

fix: keep attr `config` for class `App`

---

docs/cli.rst
docs/conf.py
docs/index.rst
idf_build_apps/main.py
idf_build_apps/utils.py
pyproject.toml

in bash script, there's no way to distinguish if one variable is None or empty string by one statement "var="
Change from nargs=* to semicolon separated string

feat!: better differentiate the None and the empty list

---

idf_build_apps/app.py
tests/conftest.py
tests/test_build.py

fix: stop recursively copy when work dir in app dir

---

.pre-commit-config.yaml
docs/find_build.md
idf_build_apps/__init__.py
idf_build_apps/app.py
idf_build_apps/build_job.py
idf_build_apps/config.py
idf_build_apps/constants.py
idf_build_apps/finder.py
idf_build_apps/junit/report.py
idf_build_apps/log.py
idf_build_apps/main.py
idf_build_apps/manifest/manifest.py
idf_build_apps/manifest/soc_header.py
idf_build_apps/utils.py
pyproject.toml
tests/test_finder.py

fix: improve logging output. Differentiate print and logging.info

---

idf_build_apps/app.py
idf_build_apps/config.py
idf_build_apps/constants.py
idf_build_apps/finder.py
idf_build_apps/main.py
idf_build_apps/manifest/manifest.py
idf_build_apps/manifest/soc_header.py
idf_build_apps/utils.py
tests/test_build.py
tests/test_finder.py

feat: replace pathlib glob to glob (RDT-605)

---

idf_build_apps/manifest/manifest.py
tests/test_manifest.py

fix: modify yaml dict shared by yaml anchors (1.x)

---

idf_build_apps/app.py
idf_build_apps/main.py
idf_build_apps/utils.py

BREAKING CHANGE:
- Turn `app.build()` arguments to kwargs
This is an alternative approach to partially support #100 
Lighter solution than #104

feat: support custom `_pre_build`, `_post_build` in App instances

---

.pre-commit-config.yaml
docs/conf.py
idf_build_apps/__init__.py
idf_build_apps/app.py
idf_build_apps/junit/__init__.py
idf_build_apps/junit/report.py
idf_build_apps/log.py
idf_build_apps/main.py
idf_build_apps/manifest/if_parser.py
idf_build_apps/session_args.py
idf_build_apps/utils.py
pyproject.toml
tests/test_build.py
tests/test_finder.py
tests/test_manifest.py

dev: use ruff format instead of black, enable more ruff checks

---

.pre-commit-config.yaml
README.md
idf_build_apps/autocompletions.py
idf_build_apps/constants.py
idf_build_apps/main.py
idf_build_apps/utils.py
pyproject.toml

Closes https://github.com/espressif/idf-build-apps/issues/27

feat(cli): add autocompletions (RDT-810)

---

idf_build_apps/constants.py
idf_build_apps/main.py

Fix some typos in the newly added `completions` command

fix(completions): fix typos in help (RDT-821)

---

.pre-commit-config.yaml
docs/conf.py
idf_build_apps/app.py
idf_build_apps/constants.py
idf_build_apps/finder.py
idf_build_apps/junit/report.py
idf_build_apps/junit/utils.py
idf_build_apps/main.py
idf_build_apps/manifest/soc_header.py
tests/test_build.py
tests/test_finder.py

also correct `post_build` actions for succeeded with warnings builds

feat: support include_disabled_apps while find_apps

---

idf_build_apps/main.py

feat: support --output-format json while find_apps

---

.github/workflows/test-build-idf-apps.yml
idf_build_apps/main.py

feat: set more default values

---

idf_build_apps/manifest/if_parser.py
idf_build_apps/manifest/manifest.py
tests/test_finder.py
tests/test_manifest.py

This MR introduces a restriction on the consecutive use of 'or' and 'and' operators at the same level within logical expressions with warning msg. The primary goal is to enhance code readability and prevent ambiguity in logical operations.
Closes #159
I have added one more test where the mock logger was used, and verified that it was called as expected.
---
Before submitting a Pull Request, please ensure the following:

feat: warning msg for multiple or and

---

.github/workflows/test-build-idf-apps.yml
.readthedocs.yml

now sphinx.configuration is required

docs: fix sphinx build

---

idf_build_apps/args.py
tests/test_args.py

- feat: add '--disable-targets' args
- RDT-1164
---
Before submitting a Pull Request, please ensure the following:

feat: support '--disable-targets' (RDT-1166)

---

docs/en/references/config_file.rst
idf_build_apps/args.py
tests/test_args.py

- collect_size_info_filename
- collect_app_info_filename
- junitxml_filename

support: enable env vars for a few more fields

---

idf_build_apps/finder.py
tests/test_finder.py

fix: respect FolderRule.DEFAULT_BUILD_TARGETS while validating app

---

.pre-commit-config.yaml
CONTRIBUTING.md
docs/en/explanations/build_status.rst
docs/en/index.rst
idf_build_apps/app.py
idf_build_apps/args.py
idf_build_apps/finder.py
idf_build_apps/main.py
idf_build_apps/manifest/manifest.py
idf_build_apps/session_args.py
pyproject.toml
tests/test_app.py
tests/test_disable_reasons.py
tests/test_finder.py

Feat: support disable reason

---

idf_build_apps/args.py

fix: ignore warnings regex ignore empty string

---

idf_build_apps/args.py
tests/test_args.py

feat: support `--additional-build-targets`
